# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKExtension'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

end
